### PR TITLE
Add GSoC 2019 project descriptions

### PR DESCRIPTION
**Pull request by wilzbach**
Not complete yet as I'm waiting for the other students to give their permissions about publishing their full proposal and improving/updating their roadmaps.

Motivation: publishing the full GSoC student proposal as this should greatly help everyone to know what our students will be working on over the summer. Also, I think it's nice to have an archive of them for historic purposes and future students.

Individual projects: https://github.com/dlang/projects/issues?q=is%3Aissue+is%3Aopen+label%3Agsoc19

### CODE REVIEW

**Comment by thewilsonator** [comment]
PDF is not a nice format for delta revisions like git, can we rip the text out and turn it into markdown?

**Comment by wilzbach** [comment]
> PDF is not a nice format for delta revisions like git, can we rip the text out and turn it into markdown?

We could, but these documents aren't intended to be modified / updated. They are the proposal for the individual projects.

**Comment by thewilsonator** [comment]
> and improving/updating their roadmaps.

> these documents aren't intended to be modified / updated

?? Maybe its too late at night for me.

**Comment by 9il** [comment]
Probably only students their self would update the docs. We use google docs that a very nice for comments and nitpicks.

**Comment by 9il** [comment]
For the history purpose, we can ask them to write a final report in Markdown. I think they will look better and will be more informative comparing with the proposals.

**Comment by wilzbach** [comment]
> ?? Maybe its too late at night for me.

This is the initial snapshot of their proposals. As Ilya mentioned the students will keep their more up to date versions of the roadmaps in Google Doc (or other forms) and also post the monthly goals on the mailing list.

> For the history purpose, we can ask them to write a final report in Markdown.

Yes a final report is definitely on the list (and even required by Google). The idea is to publish the final report (or a condensed version) on the official D Blog for good exposure.

**Comment by RazvanN7** [comment]
closing this as it is no longer actual.

**Pull request closed without merging**
