### PR TITLE
Student expectations

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Thanks!

**Comment by burner** [comment]
you are welcome

**Comment by wilzbach** [comment]
@thewilsonator:

1) this collection isn't only intended for students
2) what do you expect as possible answers to your question?

**Comment by thewilsonator** [comment]
1 I know. Hence "If applicable".

2. as a counterpart to "How does this project help the D community?" Why should the student consider doing this project, how will it help them progress their skills and experiences.

**Comment by wilzbach** [comment]
> 1 I know. Hence "If applicable".

that's in the wrong line

> as a counterpart to "How does this project help the D community?" [...]

Yeah I understood this, but I am just not convinced that most authors can answer this question in a good way other than "progress their D skills".

**Pull request merged**
